# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-62753964-1






# Build settings
markdown: kramdown
permalink: pretty

port: 9999

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :expanded


